version: "3.9"

services:
  controller:
    build: ./controller/
    pull_policy: build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cluster_net
  dashboard:
    build: ./dashboard/
    pull_policy: build
    depends_on:
      - controller
    ports:
      - "3000:3000"
    environment:
      - "ENDPOINT=http://controller:25580/status"
    networks:
      - cluster_net
  proxy:
    image: ems-proxy
    pull_policy: build
    depends_on:
      - controller
    ports:
      - 25565:25577
    environment:
      - "CONTROLLER_IP=controller"
    networks:
      - cluster_net

networks:
  cluster_net:
    driver: bridge
    name: ems_network
